// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dent/elections/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_717acb0c0988cbe7, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_717acb0c0988cbe7, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryIsVoterRegisteredRequest is request type for the Query/IsVoterRegistered RPC method.
type QueryIsVoterRegisteredRequest struct {
	WalletAddress string `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
}

func (m *QueryIsVoterRegisteredRequest) Reset()         { *m = QueryIsVoterRegisteredRequest{} }
func (m *QueryIsVoterRegisteredRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIsVoterRegisteredRequest) ProtoMessage()    {}
func (*QueryIsVoterRegisteredRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_717acb0c0988cbe7, []int{2}
}
func (m *QueryIsVoterRegisteredRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsVoterRegisteredRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsVoterRegisteredRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsVoterRegisteredRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsVoterRegisteredRequest.Merge(m, src)
}
func (m *QueryIsVoterRegisteredRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsVoterRegisteredRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsVoterRegisteredRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsVoterRegisteredRequest proto.InternalMessageInfo

func (m *QueryIsVoterRegisteredRequest) GetWalletAddress() string {
	if m != nil {
		return m.WalletAddress
	}
	return ""
}

// QueryIsVoterRegisteredResponse is response type for the Query/IsVoterRegistered RPC method.
type QueryIsVoterRegisteredResponse struct {
	WalletAddress     string `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	IsVoterRegistered bool   `protobuf:"varint,2,opt,name=is_voter_registered,json=isVoterRegistered,proto3" json:"is_voter_registered,omitempty"`
}

func (m *QueryIsVoterRegisteredResponse) Reset()         { *m = QueryIsVoterRegisteredResponse{} }
func (m *QueryIsVoterRegisteredResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIsVoterRegisteredResponse) ProtoMessage()    {}
func (*QueryIsVoterRegisteredResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_717acb0c0988cbe7, []int{3}
}
func (m *QueryIsVoterRegisteredResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsVoterRegisteredResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsVoterRegisteredResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsVoterRegisteredResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsVoterRegisteredResponse.Merge(m, src)
}
func (m *QueryIsVoterRegisteredResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsVoterRegisteredResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsVoterRegisteredResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsVoterRegisteredResponse proto.InternalMessageInfo

func (m *QueryIsVoterRegisteredResponse) GetWalletAddress() string {
	if m != nil {
		return m.WalletAddress
	}
	return ""
}

func (m *QueryIsVoterRegisteredResponse) GetIsVoterRegistered() bool {
	if m != nil {
		return m.IsVoterRegistered
	}
	return false
}

type QueryCandidateRequest struct {
	CandidateId uint64 `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
}

func (m *QueryCandidateRequest) Reset()         { *m = QueryCandidateRequest{} }
func (m *QueryCandidateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCandidateRequest) ProtoMessage()    {}
func (*QueryCandidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_717acb0c0988cbe7, []int{4}
}
func (m *QueryCandidateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCandidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCandidateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCandidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCandidateRequest.Merge(m, src)
}
func (m *QueryCandidateRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCandidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCandidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCandidateRequest proto.InternalMessageInfo

func (m *QueryCandidateRequest) GetCandidateId() uint64 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

type QueryCandidateResponse struct {
	Candidate *Candidate `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
}

func (m *QueryCandidateResponse) Reset()         { *m = QueryCandidateResponse{} }
func (m *QueryCandidateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCandidateResponse) ProtoMessage()    {}
func (*QueryCandidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_717acb0c0988cbe7, []int{5}
}
func (m *QueryCandidateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCandidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCandidateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCandidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCandidateResponse.Merge(m, src)
}
func (m *QueryCandidateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCandidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCandidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCandidateResponse proto.InternalMessageInfo

func (m *QueryCandidateResponse) GetCandidate() *Candidate {
	if m != nil {
		return m.Candidate
	}
	return nil
}

type QueryCandidatesRequest struct {
}

func (m *QueryCandidatesRequest) Reset()         { *m = QueryCandidatesRequest{} }
func (m *QueryCandidatesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCandidatesRequest) ProtoMessage()    {}
func (*QueryCandidatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_717acb0c0988cbe7, []int{6}
}
func (m *QueryCandidatesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCandidatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCandidatesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCandidatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCandidatesRequest.Merge(m, src)
}
func (m *QueryCandidatesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCandidatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCandidatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCandidatesRequest proto.InternalMessageInfo

type QueryCandidatesResponse struct {
	Candidates []*Candidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
}

func (m *QueryCandidatesResponse) Reset()         { *m = QueryCandidatesResponse{} }
func (m *QueryCandidatesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCandidatesResponse) ProtoMessage()    {}
func (*QueryCandidatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_717acb0c0988cbe7, []int{7}
}
func (m *QueryCandidatesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCandidatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCandidatesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCandidatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCandidatesResponse.Merge(m, src)
}
func (m *QueryCandidatesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCandidatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCandidatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCandidatesResponse proto.InternalMessageInfo

func (m *QueryCandidatesResponse) GetCandidates() []*Candidate {
	if m != nil {
		return m.Candidates
	}
	return nil
}

type QueryPollRequest struct {
	PollId uint64 `protobuf:"varint,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
}

func (m *QueryPollRequest) Reset()         { *m = QueryPollRequest{} }
func (m *QueryPollRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPollRequest) ProtoMessage()    {}
func (*QueryPollRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_717acb0c0988cbe7, []int{8}
}
func (m *QueryPollRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPollRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPollRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPollRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPollRequest.Merge(m, src)
}
func (m *QueryPollRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPollRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPollRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPollRequest proto.InternalMessageInfo

func (m *QueryPollRequest) GetPollId() uint64 {
	if m != nil {
		return m.PollId
	}
	return 0
}

type QueryPollResponse struct {
	Poll *Poll `protobuf:"bytes,1,opt,name=poll,proto3" json:"poll,omitempty"`
}

func (m *QueryPollResponse) Reset()         { *m = QueryPollResponse{} }
func (m *QueryPollResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPollResponse) ProtoMessage()    {}
func (*QueryPollResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_717acb0c0988cbe7, []int{9}
}
func (m *QueryPollResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPollResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPollResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPollResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPollResponse.Merge(m, src)
}
func (m *QueryPollResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPollResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPollResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPollResponse proto.InternalMessageInfo

func (m *QueryPollResponse) GetPoll() *Poll {
	if m != nil {
		return m.Poll
	}
	return nil
}

type QueryPollsRequest struct {
	IsActive bool `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (m *QueryPollsRequest) Reset()         { *m = QueryPollsRequest{} }
func (m *QueryPollsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPollsRequest) ProtoMessage()    {}
func (*QueryPollsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_717acb0c0988cbe7, []int{10}
}
func (m *QueryPollsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPollsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPollsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPollsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPollsRequest.Merge(m, src)
}
func (m *QueryPollsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPollsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPollsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPollsRequest proto.InternalMessageInfo

func (m *QueryPollsRequest) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type QueryPollsResponse struct {
	Pools []*Poll `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty"`
}

func (m *QueryPollsResponse) Reset()         { *m = QueryPollsResponse{} }
func (m *QueryPollsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPollsResponse) ProtoMessage()    {}
func (*QueryPollsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_717acb0c0988cbe7, []int{11}
}
func (m *QueryPollsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPollsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPollsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPollsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPollsResponse.Merge(m, src)
}
func (m *QueryPollsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPollsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPollsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPollsResponse proto.InternalMessageInfo

func (m *QueryPollsResponse) GetPools() []*Poll {
	if m != nil {
		return m.Pools
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "dent.elections.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "dent.elections.v1beta1.QueryParamsResponse")
	proto.RegisterType((*QueryIsVoterRegisteredRequest)(nil), "dent.elections.v1beta1.QueryIsVoterRegisteredRequest")
	proto.RegisterType((*QueryIsVoterRegisteredResponse)(nil), "dent.elections.v1beta1.QueryIsVoterRegisteredResponse")
	proto.RegisterType((*QueryCandidateRequest)(nil), "dent.elections.v1beta1.QueryCandidateRequest")
	proto.RegisterType((*QueryCandidateResponse)(nil), "dent.elections.v1beta1.QueryCandidateResponse")
	proto.RegisterType((*QueryCandidatesRequest)(nil), "dent.elections.v1beta1.QueryCandidatesRequest")
	proto.RegisterType((*QueryCandidatesResponse)(nil), "dent.elections.v1beta1.QueryCandidatesResponse")
	proto.RegisterType((*QueryPollRequest)(nil), "dent.elections.v1beta1.QueryPollRequest")
	proto.RegisterType((*QueryPollResponse)(nil), "dent.elections.v1beta1.QueryPollResponse")
	proto.RegisterType((*QueryPollsRequest)(nil), "dent.elections.v1beta1.QueryPollsRequest")
	proto.RegisterType((*QueryPollsResponse)(nil), "dent.elections.v1beta1.QueryPollsResponse")
}

func init() {
	proto.RegisterFile("dent/elections/v1beta1/query.proto", fileDescriptor_717acb0c0988cbe7)
}

var fileDescriptor_717acb0c0988cbe7 = []byte{
	// 707 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0x4f, 0x4f, 0xd4, 0x4e,
	0x18, 0xc7, 0xb7, 0xfc, 0x96, 0x85, 0x7d, 0xf8, 0x69, 0x64, 0x40, 0x20, 0x2b, 0x14, 0x18, 0x85,
	0xac, 0x4b, 0xec, 0x2c, 0x6b, 0x34, 0xc6, 0x10, 0x0d, 0xf8, 0x27, 0x72, 0xd3, 0x9a, 0x98, 0x68,
	0x4c, 0x36, 0xc3, 0x76, 0xb2, 0x69, 0x52, 0x3a, 0xa5, 0x53, 0x40, 0x42, 0xb8, 0x98, 0x78, 0x30,
	0x5e, 0x4c, 0x3c, 0x79, 0xf7, 0x3d, 0xf8, 0x16, 0x38, 0x92, 0x78, 0xf1, 0x64, 0x0c, 0xf8, 0x42,
	0x4c, 0x67, 0xa6, 0xdd, 0x65, 0xa1, 0x4b, 0xbd, 0xd1, 0xe9, 0xf7, 0xfb, 0x7c, 0x3f, 0xf3, 0xf0,
	0x3c, 0x5b, 0xc0, 0x0e, 0xf3, 0x23, 0xc2, 0x3c, 0xd6, 0x8a, 0x5c, 0xee, 0x0b, 0xb2, 0xb3, 0xbc,
	0xc1, 0x22, 0xba, 0x4c, 0xb6, 0xb6, 0x59, 0xb8, 0x67, 0x05, 0x21, 0x8f, 0x38, 0x9a, 0x88, 0x35,
	0x56, 0xaa, 0xb1, 0xb4, 0xa6, 0x32, 0xde, 0xe6, 0x6d, 0x2e, 0x25, 0x24, 0xfe, 0x4b, 0xa9, 0x2b,
	0xd3, 0x6d, 0xce, 0xdb, 0x1e, 0x23, 0x34, 0x70, 0x09, 0xf5, 0x7d, 0x1e, 0x51, 0xe5, 0x52, 0x6f,
	0x6b, 0x2d, 0x2e, 0x36, 0xb9, 0x20, 0x1b, 0x54, 0x30, 0x15, 0x92, 0x46, 0x06, 0xb4, 0xed, 0xfa,
	0x52, 0xac, 0xb5, 0xd7, 0x33, 0xd8, 0x02, 0x1a, 0xd2, 0xcd, 0xa4, 0xe0, 0x62, 0x86, 0xa8, 0x83,
	0x2b, 0x75, 0x78, 0x1c, 0xd0, 0x8b, 0x38, 0xee, 0xb9, 0x34, 0xdb, 0x6c, 0x6b, 0x9b, 0x89, 0x08,
	0xbf, 0x84, 0xb1, 0x53, 0xa7, 0x22, 0xe0, 0xbe, 0x60, 0x68, 0x05, 0x4a, 0x2a, 0x64, 0xca, 0x98,
	0x33, 0xaa, 0x23, 0x0d, 0xd3, 0x3a, 0xbf, 0x05, 0x96, 0xf2, 0xad, 0x15, 0x0f, 0x7f, 0xcd, 0x16,
	0x6c, 0xed, 0xc1, 0x4f, 0x61, 0x46, 0x16, 0x5d, 0x17, 0xaf, 0x78, 0xc4, 0x42, 0x9b, 0xb5, 0x5d,
	0x11, 0xb1, 0x90, 0x39, 0x3a, 0x15, 0x2d, 0xc0, 0xe5, 0x5d, 0xea, 0x79, 0x2c, 0x6a, 0x52, 0xc7,
	0x09, 0x99, 0x50, 0x31, 0x65, 0xfb, 0x92, 0x3a, 0x5d, 0x55, 0x87, 0x78, 0x17, 0xcc, 0xac, 0x3a,
	0x9a, 0x33, 0x5f, 0x21, 0x64, 0xc1, 0x98, 0x2b, 0x9a, 0x3b, 0x71, 0x91, 0x66, 0x98, 0x56, 0x99,
	0x1a, 0x98, 0x33, 0xaa, 0xc3, 0xf6, 0xa8, 0xdb, 0x5b, 0x1e, 0xdf, 0x87, 0xab, 0x32, 0xf8, 0x11,
	0xf5, 0x1d, 0xd7, 0xa1, 0x11, 0x4b, 0xc0, 0xe7, 0xe1, 0xff, 0x56, 0x72, 0xd6, 0x74, 0x1d, 0x99,
	0x56, 0xb4, 0x47, 0xd2, 0xb3, 0x75, 0x07, 0xbf, 0x86, 0x89, 0x5e, 0xaf, 0x86, 0x7d, 0x08, 0xe5,
	0x54, 0xa8, 0xfb, 0x3a, 0x9f, 0xd5, 0xd7, 0x8e, 0xbb, 0xe3, 0xc1, 0x53, 0xbd, 0xa5, 0xd3, 0x7f,
	0xe3, 0x5b, 0x98, 0x3c, 0xf3, 0x46, 0xa7, 0xae, 0x02, 0xa4, 0x15, 0xe2, 0xf6, 0xfc, 0x97, 0x2f,
	0xb6, 0xcb, 0x84, 0x97, 0xe0, 0x8a, 0x1a, 0x12, 0xee, 0x79, 0x49, 0x27, 0x26, 0x61, 0x28, 0xe0,
	0x9e, 0xd7, 0x69, 0x42, 0x29, 0x7e, 0x5c, 0x77, 0xf0, 0x13, 0x18, 0xed, 0x12, 0x6b, 0x88, 0x3a,
	0x14, 0xe3, 0xd7, 0xfa, 0xd6, 0xd3, 0x99, 0xd3, 0x14, 0x7b, 0xa4, 0x12, 0xd7, 0xbb, 0xca, 0x24,
	0xd7, 0x44, 0xd7, 0xa0, 0xec, 0x8a, 0x26, 0x6d, 0x45, 0xee, 0x8e, 0xea, 0xe0, 0xb0, 0x3d, 0xec,
	0x8a, 0x55, 0xf9, 0x8c, 0x9f, 0x25, 0x03, 0xae, 0x1c, 0x3a, 0xb9, 0x01, 0x83, 0x01, 0xe7, 0x5e,
	0x72, 0xf3, 0xfe, 0xd1, 0x4a, 0xda, 0xf8, 0x3e, 0x04, 0x83, 0xb2, 0x14, 0xfa, 0x68, 0x40, 0x49,
	0x8d, 0x38, 0xaa, 0x65, 0x39, 0xcf, 0x6e, 0x55, 0x65, 0x29, 0x97, 0x56, 0x11, 0xe2, 0xc5, 0xf7,
	0x3f, 0xfe, 0x7c, 0x19, 0x98, 0x43, 0x26, 0xe9, 0xbb, 0xee, 0xe8, 0xd0, 0x80, 0xd1, 0x33, 0x9b,
	0x80, 0xee, 0xf4, 0x8d, 0xca, 0xda, 0xc0, 0xca, 0xdd, 0x7f, 0xb5, 0x69, 0xd8, 0xc7, 0x12, 0xf6,
	0x01, 0x5a, 0xc9, 0x82, 0x3d, 0x67, 0xcf, 0xc8, 0xfe, 0xe9, 0x1d, 0x3d, 0x40, 0xdf, 0x0c, 0x28,
	0xa7, 0xa3, 0x86, 0x6e, 0xf5, 0x65, 0xe9, 0xdd, 0xc1, 0x8a, 0x95, 0x57, 0xae, 0x91, 0xef, 0x49,
	0xe4, 0x06, 0xaa, 0x67, 0x21, 0xa7, 0x93, 0x4e, 0xf6, 0xbb, 0x97, 0xfb, 0x00, 0x7d, 0x35, 0x00,
	0x3a, 0x1b, 0x85, 0x72, 0x06, 0xa7, 0x53, 0x40, 0x72, 0xeb, 0x35, 0x69, 0x4d, 0x92, 0xde, 0x40,
	0xf8, 0x42, 0x52, 0x81, 0x3e, 0x19, 0x50, 0x8c, 0x67, 0x16, 0x55, 0xfb, 0xcf, 0x5a, 0x67, 0x65,
	0x2b, 0x37, 0x73, 0x28, 0x35, 0x89, 0x25, 0x49, 0xaa, 0x68, 0x31, 0x73, 0x26, 0xb9, 0xe7, 0x91,
	0x7d, 0xfd, 0x0b, 0x70, 0x80, 0x3e, 0x18, 0x30, 0x28, 0xf7, 0x0e, 0x5d, 0x1c, 0x92, 0xf6, 0xa7,
	0x96, 0x47, 0xaa, 0x81, 0x16, 0x24, 0xd0, 0x2c, 0x9a, 0xc9, 0x06, 0xe2, 0x9e, 0x58, 0xab, 0x1f,
	0x1e, 0x9b, 0xc6, 0xd1, 0xb1, 0x69, 0xfc, 0x3e, 0x36, 0x8d, 0xcf, 0x27, 0x66, 0xe1, 0xe8, 0xc4,
	0x2c, 0xfc, 0x3c, 0x31, 0x0b, 0x6f, 0xe4, 0x37, 0x9c, 0xbc, 0xeb, 0x72, 0x46, 0x7b, 0x01, 0x13,
	0x1b, 0x25, 0xf9, 0x75, 0xbc, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0x06, 0xd0, 0x48, 0xd3, 0x08,
	0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	IsVoterRegistered(ctx context.Context, in *QueryIsVoterRegisteredRequest, opts ...grpc.CallOption) (*QueryIsVoterRegisteredResponse, error)
	Candidate(ctx context.Context, in *QueryCandidateRequest, opts ...grpc.CallOption) (*QueryCandidateResponse, error)
	Candidates(ctx context.Context, in *QueryCandidatesRequest, opts ...grpc.CallOption) (*QueryCandidatesResponse, error)
	Poll(ctx context.Context, in *QueryPollRequest, opts ...grpc.CallOption) (*QueryPollResponse, error)
	Polls(ctx context.Context, in *QueryPollsRequest, opts ...grpc.CallOption) (*QueryPollsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/dent.elections.v1beta1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) IsVoterRegistered(ctx context.Context, in *QueryIsVoterRegisteredRequest, opts ...grpc.CallOption) (*QueryIsVoterRegisteredResponse, error) {
	out := new(QueryIsVoterRegisteredResponse)
	err := c.cc.Invoke(ctx, "/dent.elections.v1beta1.Query/IsVoterRegistered", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Candidate(ctx context.Context, in *QueryCandidateRequest, opts ...grpc.CallOption) (*QueryCandidateResponse, error) {
	out := new(QueryCandidateResponse)
	err := c.cc.Invoke(ctx, "/dent.elections.v1beta1.Query/Candidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Candidates(ctx context.Context, in *QueryCandidatesRequest, opts ...grpc.CallOption) (*QueryCandidatesResponse, error) {
	out := new(QueryCandidatesResponse)
	err := c.cc.Invoke(ctx, "/dent.elections.v1beta1.Query/Candidates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Poll(ctx context.Context, in *QueryPollRequest, opts ...grpc.CallOption) (*QueryPollResponse, error) {
	out := new(QueryPollResponse)
	err := c.cc.Invoke(ctx, "/dent.elections.v1beta1.Query/Poll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Polls(ctx context.Context, in *QueryPollsRequest, opts ...grpc.CallOption) (*QueryPollsResponse, error) {
	out := new(QueryPollsResponse)
	err := c.cc.Invoke(ctx, "/dent.elections.v1beta1.Query/Polls", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	IsVoterRegistered(context.Context, *QueryIsVoterRegisteredRequest) (*QueryIsVoterRegisteredResponse, error)
	Candidate(context.Context, *QueryCandidateRequest) (*QueryCandidateResponse, error)
	Candidates(context.Context, *QueryCandidatesRequest) (*QueryCandidatesResponse, error)
	Poll(context.Context, *QueryPollRequest) (*QueryPollResponse, error)
	Polls(context.Context, *QueryPollsRequest) (*QueryPollsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) IsVoterRegistered(ctx context.Context, req *QueryIsVoterRegisteredRequest) (*QueryIsVoterRegisteredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsVoterRegistered not implemented")
}
func (*UnimplementedQueryServer) Candidate(ctx context.Context, req *QueryCandidateRequest) (*QueryCandidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Candidate not implemented")
}
func (*UnimplementedQueryServer) Candidates(ctx context.Context, req *QueryCandidatesRequest) (*QueryCandidatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Candidates not implemented")
}
func (*UnimplementedQueryServer) Poll(ctx context.Context, req *QueryPollRequest) (*QueryPollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Poll not implemented")
}
func (*UnimplementedQueryServer) Polls(ctx context.Context, req *QueryPollsRequest) (*QueryPollsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Polls not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dent.elections.v1beta1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_IsVoterRegistered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIsVoterRegisteredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IsVoterRegistered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dent.elections.v1beta1.Query/IsVoterRegistered",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IsVoterRegistered(ctx, req.(*QueryIsVoterRegisteredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Candidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Candidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dent.elections.v1beta1.Query/Candidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Candidate(ctx, req.(*QueryCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Candidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Candidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dent.elections.v1beta1.Query/Candidates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Candidates(ctx, req.(*QueryCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Poll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Poll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dent.elections.v1beta1.Query/Poll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Poll(ctx, req.(*QueryPollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Polls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPollsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Polls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dent.elections.v1beta1.Query/Polls",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Polls(ctx, req.(*QueryPollsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dent.elections.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "IsVoterRegistered",
			Handler:    _Query_IsVoterRegistered_Handler,
		},
		{
			MethodName: "Candidate",
			Handler:    _Query_Candidate_Handler,
		},
		{
			MethodName: "Candidates",
			Handler:    _Query_Candidates_Handler,
		},
		{
			MethodName: "Poll",
			Handler:    _Query_Poll_Handler,
		},
		{
			MethodName: "Polls",
			Handler:    _Query_Polls_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dent/elections/v1beta1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryIsVoterRegisteredRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsVoterRegisteredRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsVoterRegisteredRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WalletAddress) > 0 {
		i -= len(m.WalletAddress)
		copy(dAtA[i:], m.WalletAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.WalletAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryIsVoterRegisteredResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsVoterRegisteredResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsVoterRegisteredResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsVoterRegistered {
		i--
		if m.IsVoterRegistered {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.WalletAddress) > 0 {
		i -= len(m.WalletAddress)
		copy(dAtA[i:], m.WalletAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.WalletAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCandidateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCandidateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCandidateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CandidateId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CandidateId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryCandidateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCandidateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCandidateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Candidate != nil {
		{
			size, err := m.Candidate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCandidatesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCandidatesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCandidatesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryCandidatesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCandidatesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCandidatesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Candidates) > 0 {
		for iNdEx := len(m.Candidates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Candidates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryPollRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPollRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPollRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PollId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PollId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryPollResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPollResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPollResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Poll != nil {
		{
			size, err := m.Poll.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPollsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPollsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPollsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsActive {
		i--
		if m.IsActive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryPollsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPollsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPollsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Pools) > 0 {
		for iNdEx := len(m.Pools) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pools[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryIsVoterRegisteredRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.WalletAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryIsVoterRegisteredResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.WalletAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.IsVoterRegistered {
		n += 2
	}
	return n
}

func (m *QueryCandidateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CandidateId != 0 {
		n += 1 + sovQuery(uint64(m.CandidateId))
	}
	return n
}

func (m *QueryCandidateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Candidate != nil {
		l = m.Candidate.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCandidatesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryCandidatesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Candidates) > 0 {
		for _, e := range m.Candidates {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryPollRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PollId != 0 {
		n += 1 + sovQuery(uint64(m.PollId))
	}
	return n
}

func (m *QueryPollResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Poll != nil {
		l = m.Poll.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPollsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsActive {
		n += 2
	}
	return n
}

func (m *QueryPollsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Pools) > 0 {
		for _, e := range m.Pools {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIsVoterRegisteredRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsVoterRegisteredRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsVoterRegisteredRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WalletAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIsVoterRegisteredResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsVoterRegisteredResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsVoterRegisteredResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WalletAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsVoterRegistered", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsVoterRegistered = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCandidateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCandidateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCandidateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CandidateId", wireType)
			}
			m.CandidateId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CandidateId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCandidateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCandidateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCandidateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Candidate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Candidate == nil {
				m.Candidate = &Candidate{}
			}
			if err := m.Candidate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCandidatesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCandidatesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCandidatesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCandidatesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCandidatesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCandidatesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Candidates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Candidates = append(m.Candidates, &Candidate{})
			if err := m.Candidates[len(m.Candidates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPollRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPollRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPollRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PollId", wireType)
			}
			m.PollId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PollId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPollResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPollResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPollResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Poll", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Poll == nil {
				m.Poll = &Poll{}
			}
			if err := m.Poll.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPollsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPollsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPollsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsActive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsActive = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPollsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPollsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPollsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pools", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pools = append(m.Pools, &Poll{})
			if err := m.Pools[len(m.Pools)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
